import { createApi } from '@reduxjs/toolkit/query/react';
import { baseQueryWithReauth } from './baseQuery';

// Root RTK Query slice. Each domain file injects its endpoints into it
// (store/api/*Api.js) so every request shares one cache, one base query and
// one set of tags.
export const baseApi = createApi({
  reducerPath: 'api',
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    'Me',
    // auth + billing
    'Staff',
    'Role',
    'Permission',
    'Package',
    'Subscription',
    'PaymentMethod',
    'Invoice',
    'Usage',
    'Wallet',
    'ApiKey',
    'Privacy',
    'SubAccount',
    // admin
    'Customer',
    'Domain',
    'TenantSettings',
    'AdminRole',
    'AdminStaff',
    'NumberPool',
    'Template',
    'Audit',
    'Platform',
    // flow
    'Agent',
    'AgentSection',
    'Version',
    'Scenario',
    'TestRun',
    'Company',
    'Knowledge',
    'Source',
    'Tool',
    'Pronunciation',
    'Voice',
    'Team',
    'Catalog',
    // telephony / outbound / analytics
    'Number',
    'Routing',
    'Holiday',
    'Connection',
    'Call',
    'Review',
    'Scorecard',
    'Campaign',
    'CampaignContact',
    'Contact',
    'ContactList',
    'ContactField',
    'Dnd',
    'CallingRules',
    'Scheduled',
    'Trigger',
    'Analytics',
    'SavedView',
    'Export',
    'Report',
    // integration
    'Webhook',
    'Integration',
    'Booking',
    'Message',
    'Notification',
    'NotificationSettings',
    'Channel',
    'MessageTemplate',
    'Conversation',
    'Broadcast',
  ],
  endpoints: () => ({}),
});
